id: PACC6A79C
initial_creation_type: input
source_metadata:
  title: Yamāntaka Series
  language: bo
  description: 'Texts related to Yamāntaka (gshin rje gshed), the wrathful form of
    Mañjuśrī:'
  volume:
    7d04926d0fd74730b4444474fb170932:
      title: Daily Practice of Mañjuśrī Yamāntaka
      parent: Sādhanas
    585e8557020e45d88cd0b735e79196ec:
      title: The Method to Pacify All Epidemics, Illnesses and Pandemics from the
        Sixty Solitary Forms of Yamāntaka
      parent: Sādhanas
created_at: '2022-03-01T06:35:53.231224'
last_modified_at: '2022-03-01T06:35:53.231226'
